apiVersion: apps/v1
kind: Deployment
metadata:
  # Nome mais curto e consistente
  name: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
      - name: student-service-container # Nome mais descritivo
        # O placeholder continua, o pipeline irá substituí-lo corretamente agora
        image: imagem-placeholder
        ports:
        # Dando um nome à porta para referência no Service
        - name: http
          containerPort: 8080
        # Health Probes: Garante que o tráfego só seja enviado para pods saudáveis.
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http # Referencia o nome da porta
          initialDelaySeconds: 20 # Aumentado para dar mais tempo para o Spring Boot iniciar
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http # Referencia o nome da porta
          initialDelaySeconds: 10 # Aumentado
          periodSeconds: 10
        # Gerenciamento de Recursos: Garante a estabilidade do cluster.
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Externalização de Configuração: Carrega configurações do ambiente K8s.
        envFrom:
        - configMapRef:
            name: student-service-config
        # A referência a 'secretRef' foi removida, pois não criamos um Secret.
        # Se precisar de segredos no futuro, pode adicionar o bloco de volta.