apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  # Tipo padrão, só acessível de dentro do cluster
  type: ClusterIP
  ports:
  - port: 5432        # A porta que o Service expõe
    targetPort: 5432  # A porta do contêiner (StatefulSet)
  selector:
    app: postgres # Seleciona os pods com a label 'app: postgres'