apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: manual # Deve ser o MESMO nome do PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Deve ser o MESMO tamanho (ou menor) do PV