apiVersion: v1
kind: Service
metadata:
  # Nome mais curto e consistente
  name: student-service
spec:
  selector:
    app: student-service
  ports:
    - protocol: TCP
      port: 8080
      # Usa o nome da porta definido no deployment, mais robusto
      targetPort: http
  type: NodePort