# Nome do Workflow
name: Build and Deploy to K3s

# Gatilho: Executa sempre que houver um push na branch 'main'
on:
  push:
    branches:
      - main

env:
  # Define o nome da imagem para ser usado em ambos os jobs
  IMAGE_NAME: ${{ github.repository }}

jobs:
  #----------------------------------------------------
  # JOB 1: Construir a imagem Docker e enviar para o GHCR
  #----------------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  #----------------------------------------------------
  # JOB 2: Fazer o deploy da imagem no Kubernetes
  #----------------------------------------------------
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          
      # =================================================================
      # !!!!! PASSO DE DEPURAÇÃO TEMPORÁRIO !!!!!
      # =================================================================
      - name: DEBUG - Verify Kubeconfig Content
        run: |
          echo "====================== INÍCIO DA DEPURAÇÃO ======================"
          echo " "
          echo ">>> Verificando se o arquivo ~/.kube/config existe e tem conteúdo:"
          ls -l ~/.kube/config
          echo " "
          
          echo ">>> Imprimindo o conteúdo COMPLETO do arquivo ~/.kube/config:"
          cat ~/.kube/config
          echo " "
          
          echo "======================= FIM DA DEPURAÇÃO ======================="
      # =================================================================
        
      - name: Deploy to K3s
        run: |
          echo "Atualizando a imagem para: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          sed -i "s|image:.*|image: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          
          kubectl apply -f k8s/
          
          echo "Verificando o status do deploy..."
          sleep 15
          kubectl get pods
          kubectl get services