name: 'CI/CD Pipeline Principal'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ds6-student-service/**'

jobs:
  call-reusable-workflow:
    uses: distrischool-6/.github/workflows/reusable-java-ci.yml@main
    permissions:
      contents: read
      packages: write
    with:
      service-name: 'ds6-student-service'
    secrets:
      inherit
