name: 'CI/CD Pipeline Principal'

on:
  push:
    branches:
      - 'main'

permissions: 
  contents: read
  packages: write


jobs:
  # Job 1: Build, Teste e Push da Imagem Docker
  build:
    uses: distrischool-6/.github/.github/workflows/reusable-java-k8s-pipeline.yml@main
    with:
      service-name: 'ds6-student-service'
    secrets: 
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}